// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e20d7820-222b-4edd-9012-abe3b45b3f9c";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSensorChange();
void onSocket1Change();
void onSocket2Change();
void onSocketChange();
void onSchdeChange();

String sensor;
CloudSwitch socket1;
CloudSwitch socket2;
int socket;
CloudSchedule schde;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(sensor, READWRITE, ON_CHANGE, onSensorChange);
  ArduinoCloud.addProperty(socket1, READWRITE, ON_CHANGE, onSocket1Change);
  ArduinoCloud.addProperty(socket2, READWRITE, ON_CHANGE, onSocket2Change);
  ArduinoCloud.addProperty(socket, READWRITE, ON_CHANGE, onSocketChange);
  ArduinoCloud.addProperty(schde, READWRITE, ON_CHANGE, onSchdeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
